version: "2"
linters:
  settings:
    errcheck:
      check-type-assertions: false
      check-blank: false
      exclude-functions:
        - io/ioutil.ReadFile
        - io.Copy(*bytes.Buffer)
        - io.Copy(os.Stdout)
        - github.com/UniversityRadioYork/2016-site/utils.RenderTemplate
        - (*net/http.Request).ParseForm
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
