#!/bin/sh

# $FreeBSD$
#
# PROVIDE: twentysixteensite
# KEYWORD: shutdown
#
# This file runs 2016-site as a service on a FreeBSD system.
# Modify paths as necessary and install in /usr/local/etc/rc.d/
#
# Add the following lines to /etc/rc.conf.local or /etc/rc.conf
# to enable this service:
#
# twentysixteensite_enable (bool): Set to NO by default.
#                  Set it to YES to enable hawk.

. /etc/rc.subr

name=twentysixteensite
rcvar=twentysixteensite_enable
twentysixteensite_enable=${twentysixteensite_enable:-"NO"}

twentysixteensite_chdir='/usr/local/www/2016-site' # TODO: This shouldn't be necessary

pidfile='/var/run/2016-site.pid'
logfile='/var/log/2016-site.log'

command='/usr/local/www/2016-site/2016-site'
twentysixteensite_program='/usr/sbin/daemon'
command_args="-u website -o /var/log/2016-site.log -P ${pidfile} ${command} 2>&1"

load_rc_config "$name"
run_rc_command "$1"
