name: Go

on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ development ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: WillAbides/setup-go-faster@v1.14.0
      with:
        go-version: 1.17

    - run: ls ${{ github.workspace }}

    - name: Build
      run: go build -v ./...
      working-directory: ${{ github.workspace }}

    - name: Test
      run: go test -v ./...
      working-directory: ${{ github.workspace }}

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: WillAbides/setup-go-faster@v1.14.0
        with:
          go-version: 1.17

      - name: Lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest
          working-directory: ${{ github.workspace }}
